Bank
valera5505/SPbU pull request #185
Opened 2017-03-17 10:53 UTC by PolyProgrammist

2017-03-17 11:10 UTC, glorko reviewed
Комменты под кодом

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/Client.java
> +public class Client {
Поля private, геттеры сеттеры нннада

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/Singleton.java
> +public class Singleton {
наверное должен быть static и с адекватным именем. иначе по сути это не синглтон.
https://ru.wikipedia.org/wiki/%D0%9E%D0%B4%D0%B8%D0%BD%D0%BE%D1%87%D0%BA%D0%B0_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
Лучше дать ему более информативное имя

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/Singleton.java
> +    ArrayList<Client> aclient = new ArrayList<Client>();
List<Some> some = new ArrayList<>(); 
избегаем ипоминания классов там где должны быть упомянуты интерфейсы

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/FileBaseInterpreter.java
> +    private void addCredit(String s) {
не лучше сделать private Credit parseCredit(String s)? Более ООП стиль. у нас нету неявного изменения внутреннего состояния (в нашем случае мы внутри метода ничего никуда не добавляет)

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/FileBaseInterpreter.java
> +    private void addClient(String s) {
то же самое, две разные логики в одном методе. парсим и добавляем.

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/Credit.java
> +public class Credit {
геттеры сеттеры приватные поля (геттеры и сеттеры умеет генерить идея)

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/FileBaseInterpreter.java
> +    ArrayList<Client> acl;
List<Client>, имя должно быть осмысленным

2017-03-17 11:10 UTC, glorko commented on Volodin/MyBank/ClientHelper.java
> +    public void printRandomLosses(){
эт зачем?:)

2017-03-17 13:25 UTC, PolyProgrammist commented on Volodin/MyBank/Client.java
> +public class Client {
Идея сгенерировала

2017-03-17 13:26 UTC, PolyProgrammist commented on Volodin/MyBank/Credit.java
> +public class Credit {
Идея сгенерировала

2017-03-17 13:26 UTC, PolyProgrammist commented on Volodin/MyBank/Singleton.java
> +public class Singleton {
Синглтон сделан

2017-03-17 13:27 UTC, PolyProgrammist commented on Volodin/MyBank/Singleton.java
> +    ArrayList<Client> aclient = new ArrayList<Client>();
Теперь в объявлениях при возможности интерфейсы вместо классов

2017-03-17 13:27 UTC, PolyProgrammist commented on Volodin/MyBank/FileBaseInterpreter.java
> +    ArrayList<Client> acl;
Объект удален

2017-03-17 13:28 UTC, PolyProgrammist commented on Volodin/MyBank/FileBaseInterpreter.java
> +    private void addCredit(String s) {
Метод разделен, а также несколько других

2017-03-17 13:29 UTC, PolyProgrammist commented on Volodin/MyBank/ClientHelper.java
> +    public void printRandomLosses(){
Для того чтобы показать, что третья функция работает

2017-03-24 11:07 UTC, glorko commented on Volodin/MyBank/Client.java
> +    private int pasport;
Номер паспорта это точно не int

2017-03-24 11:07 UTC, glorko commented on Volodin/MyBank/ExcelWriter.java
> +                "ID", "�������", "���", "��������", "�������", "�������", "���� ��������", "������ �������"
Я тоже это вижу?

2017-03-24 11:08 UTC, glorko commented on Volodin/MyBank/Client.java
> +    private int pasport;
И все таки корректно passport

2017-03-24 18:12 UTC, PolyProgrammist commented on Volodin/MyBank/ExcelWriter.java
> +                "ID Клиента", "Сумма", "Сумма к оплате", "Оплачено", "Процент", "Дата закрытия"
Не нашел нормального варианта изменения кодировки, изменено с помощью веб-версии гитхаб

2017-03-24 18:12 UTC, PolyProgrammist commented on Volodin/MyBank/Client.java
> +    private String passport;
passport теперь строка

2017-03-24 18:16 UTC, PolyProgrammist commented on Volodin/MyBank/Client.java
> +    private int pasport;
исправлено

2017-04-14 11:08 UTC, glorko requested changes
А где последний коммит?:)

2017-05-26 11:32 UTC, glorko approved these changes

2017-06-05 16:13 UTC, merged