banksys
valera5505/SPbU pull request #186
Opened 2017-03-24 11:18 UTC by stspbu

2017-04-14 11:10 UTC, glorko requested changes

2017-04-14 11:10 UTC, glorko commented on Bushev/Java/1_bankSys/java/app/Algo.java
> +    public static String getInt(String data){
Для чего это? Просто достает числа из строки?

2017-04-14 11:10 UTC, glorko commented on Bushev/Java/1_bankSys/java/app/ClientHelper.java
> +    public static void showUnpaid(ArrayList<Client> clients, boolean showUsers){
тут тоже что-то сомнительное. Я, если честно, не уловил идею

2017-04-14 11:21 UTC, stspbu commented on Bushev/Java/1_bankSys/java/app/ClientHelper.java
> +    public static void showUnpaid(ArrayList<Client> clients, boolean showUsers){
Это просто вывод количества должников и невыплаченных кредитов. Раньше этот метод использовался непосредственно, сейчас - на случай, если что-то пойдёт не так, и надо будет узнать, что за информация хранится в storage.

2017-04-14 11:23 UTC, stspbu commented on Bushev/Java/1_bankSys/java/app/Algo.java
> +    public static String getInt(String data){
Да. Простой integer.parseInt строку вида "+7-123-345...." не обработает. Поэтому я сначала регуляркой убираю все лишнее, кроме цифр.

2017-05-04 12:57 UTC, glorko approved these changes

2017-05-04 12:57 UTC, merged